### PR TITLE
Add support for TRACY_DEBUGINFOD

### LINKED ISSUE #120: Support for TRACY_DEBUGINFOD
There doesn't seem to be a way to enable the TRACY_DEBUGINFOD feature.

### PR DESCRIPTION
**Pull request by mahkoh**
Closes #120

### CODE REVIEW

**Comment by nagisa** [comment]
Thanks!

**Comment by nagisa** [comment]
Hm, looks like the doc build fails -- something needs to be adjusted to make the header available...

**Comment by mahkoh** [comment]
Added the package to the workflow.

**Comment by mahkoh** [comment]
But neither of those will work on windows. Not sure how to handle this.

**Comment by mahkoh** [comment]
This should work now. The feature is not being tested so there is no need to install the package in that workflow.

**Comment by nagisa** [comment]
Do you know if docs.rs has this package installed? If not, we need to adjust the configuration for docs.rs too.

**Comment by nagisa** [comment]
Looks like not: https://github.com/rust-lang/crates-build-env/blob/master/linux/packages.txt

**Comment by mahkoh** [comment]
Should be handled via https://github.com/rust-lang/docs.rs/issues/147#issuecomment-648844656

**Review by nagisa — APPROVED** [review]

**Pull request merged**
