### PR TITLE
Avoid removing pub from members named type

### LINKED ISSUE #39: __tracy_gpu_new_context_data has private field making it unconstructable
Oddly it seems to have a completely private field which we need to fill to be able to call the function. I'm not sure what caused bindgen to emit this one field as private.

https://docs.rs/tracy-client-sys/latest/tracy_client_sys/struct.___tracy_gpu_new_context_data.html

### PR DESCRIPTION
**Pull request by cwfitzgerald**
Closes #39

Not sure if there's anything else I need to do to make the regeneration happen right.

### CODE REVIEW

**Comment by cwfitzgerald** [comment]
Alright, I'll just wait for CI to regen then, thanks!

**Comment by nagisa** [comment]
Merged, thanks!

**Comment by Imberflur** [comment]
```sh
's/pub type /type/g'
                ^
```
this probably needs a space here to avoid removing the space

**Comment by nagisa** [comment]
Yeah, I have added that in a follow-up [here](https://github.com/nagisa/rust_tracy_client/commit/54ebfa92a59928eefae5030a76588312300290b0).

**Comment by Ralith** [comment]
A more general/robust solution than sed might be to pass allowlist regexps to bindgen.

**Comment by nagisa** [comment]
I remember trying to do that back when this was initially added. I don't remember exactly why it didn't work but it must have been either one of:

1. It doesn't work for system header stuff that the API depends on and bindgen still publicly exports the types;
2. Bindings no longer compile due to missing type definitions.

**Pull request merged**
